#!/bin/bash
conf=$HOME/.config/wine_helper/settings.conf

VER="1.6.2"

RUNTIME="$HOME/.steam/runtime/run.sh"
dir="/opt"
default_prefix=".wine64"
wine_prefixes_dir="$HOME/.local/share/wine_prefix/"

if [ -f $conf ]; then
	RUNTIME=`awk -F "=" '/runtime_command/ {print $2}' $conf`
	dir=`awk -F "=" '/wine_dir/ {print $2}' $conf`
	default_prefix=`awk -F "=" '/default_prefix/ {print $2}' $conf`
	wine_prefixes_dir=`awk -F "=" '/wine_prefixes_dir/ {print $2}' $conf`
fi

wine_ver_get=`ls $dir | sort --version-sort | sed '/wine/!d; $!d'` # get the lasted version of wine in dir, e.g. wine_1.8.0
wine_path=$dir$wine_ver_get"/bin/"

function help() 
{
	echo "Usage: wine PROGRAM [ARGUMENTS...]  		Run the specified program
       wine -h			     		Display wine script help
       wine -v					Display wine script version
       wine --version				Display (lastes you have) wine version
       wine --help                   		Display wine help and exit
       wine --version               		Output version information and exit
       wine --patches               		Output patch information and exit
       wine --check-libs            		Checks if shared libs are installed
       wine -np|--new-prefix	     		New prefix
       wine -p|--prefix				Set wine prefix (if you have problems with this, use WINEPREFIX=* instead)
       wine -a|--arch				Set wine arch (if you have problems with this, use ARCH=* instead)
       wine -wvs|--wine-version-set		Set wine version to use
       wine --check-wine-version		Check if wine-starging need to be updated
       wine --set-shortcut			Set shortcut
       
       WINEPREFIX=/prefix/path			Use specific prefix
       WINEARCH=win32				Use wine 32bit prefix
       ARCH=win32				Use 32bit wine binaries
       WINEDLLOVERRIDES=[dlls]			Override dlls, e.g.:
						'd3dx9=n,b;C:\user\d3dx9=b;...',
						n -- native, b -- blutin
       WINEDEBUG=[channels]			Use debug, e.g.: +all,-relay; warn+heap

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY (c) 2015 Volk_Milit"
}

if [ "$1" = "-v" ]; then
	echo "WINE helper version is $VER"
	exit 0
elif [ "$1" = "-h" ]; then
	help
	exit 0
elif [ "$1" = "--check-wine-version" ]; then
	wine-update
	exit 0
elif [ "$1" = "--set-shortcut" ]; then
	wine-shortcut
	exit 0
fi

for i in "$@"; do
	case $i in
		-wvs=*|--wine-ver-set=*)
		wine_path=$dir"wine_${i#*=}/bin/"
		shift
		;;
		
		-np|--new-prefix)
		WINEPREFIX=$WINEPREFIX $wine_path$ww wineboot
		shift
		;;
		
		-p=*|--prefix=*)
		WINEPREFIX=$wine_prefixes_dir"${i#*=}"
		shift
		;;
		
		-a=*|--arch=*)
		ARCH="${i#*=}"
		shift
		;;
		
		*)		
		#help
		#exit 0
		;;
esac
done

if [ -z "$WINEPREFIX" ]; then
	WINEPREFIX=$wine_prefixes_dir$default_prefix
fi

prefix=`awk -F "=" '/#arch/ {print $2}' $WINEPREFIX/user.reg`

if [[ ! -z "$ARCH" || "$prefix" = "win32" ]]; then
	ww="wine"
	echo "msg: Use 32bit wine"
else
	ww="wine64"
	echo "msg: Use 64bit wine (by default)"
fi

if [ -z $RUNTIME ]; then
	echo "msg: Use NO runtime. Remember, if you don't use multilib, some 32bit app may work incorrectly."
else
	echo "msg: Use \"$RUNTIME\" command to provide runtime."
fi

wine_ver=`echo $wine_path | sed 's/[\/_optwineb]//g'`

echo "msg: running wine verion $wine_ver" 
WINEPREFIX=$WINEPREFIX $RUNTIME $wine_path$ww $1
