#!/bin/bash
conf=$HOME/.config/wine_helper/settings.conf

VER="1.6.0"

RUNTIME="$HOME/.steam/runtime/run.sh"
dir="/opt"
default_prefix=".wine64"
wine_prefixes_dir="$HOME/.local/share/wine_prefix/"$default_prefix

if [ -f $conf ]; then
	RUNTIME=`awk -F "=" '/runtime_command/ {print $2}' $conf`
	dir=`awk -F "=" '/wine_dir/ {print $2}' $conf`
	default_prefix=`awk -F "=" '/default_prefix/ {print $2}' $conf`
	wine_prefixes_dir=`awk -F "=" '/wine_prefixes_dir/ {print $2}' $conf`
fi

wine_ver_get=`ls $dir | sort --version-sort | sed '/wine/!d; $!d'` # get the lasted version of wine in dir, e.g. wine_1.8.0
wine_path=$dir$wine_ver_get"/bin/"

function help() 
{
	echo "Usage: wine PROGRAM [ARGUMENTS...]  		Run the specified program
       wine --h			     		Display wine script help
       wine --ver				Display wine script version
       wine --version				Display (lastes you have) wine version
       wine --help                   		Display wine help and exit
       wine --version               		Output version information and exit
       wine --patches               		Output patch information and exit
       wine --check-libs            		Checks if shared libs are installed
       wine --new-prefix	     		New prefix
       wine --check-wine-version		Check if wine-starging need to be updated
       
       WINEPREFIX=/prefix/path			Use specific prefix
       WINEARCH=win32				Use wine 32bit prefix
       ARCH=win32				Use 32bit wine binaries
       WINEDLLOVERRIDES=[dlls]			Override dlls, e.g.:
						'd3dx9=n,b;C:\user\d3dx9=b;...',
						n -- native, b -- blutin
       WINEDEBUG=[channels]			Use debug, e.g.: +all,-relay; warn+heap
       WINE=[wine version]			Use specific wine version

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY (c) 2015 Volk_Milit"
}

function yesno()
{
	read ans
		
	case $ans in
		"no") rm /tmp/wine-staging.html; exit 0;;
		"n") rm /tmp/wine-staging.html; exit 0;;
		"N") rm /tmp/wine-staging.html; exit 0;;
		"yes") getLastesWine;;
		"y") getLastesWine;;
		"Y") getLastesWine;;
		*) echo "Put (y)es or (n)o!"; yesno;;
	esac
}

function checkWineVersion()
{
	# get wine-staging page
	wget -qO - http://cdn.fds-team.de/stable/debian/pool/main/w/wine-staging/ > /tmp/wine-staging.html
	
	v=$(cat /tmp/wine-staging.html | sed -e :a -e 's/<[^>]*>//g;/</N;//ba' | cut -f 1 -d ' ' | sed '/dev/d;/dbg/d;/winehq/d;/compat/d'\
 | grep `lsb_release --codename | cut -f 2` | tail -n 4 | sed '3!D' | sed -E 's/amd64//g;s/[^.0-9]//g' | rev | cut -c 2- | rev)
 
	if [ "wine_"$v = $wine_ver_get ]; then
		echo "You have lastes wine version at this moment: $wine_ver_get"
		rm /tmp/wine-staging.html
		exit 0
	else
		echo -e "New version ($v) are avalable! Do you want to download it?\n[Y(es)/n(o)]:"
		yesno
	fi
}

function getLastesWine()
{	
	echo "================================"
	echo "Downloading lastes wine-staging"
	echo "================================"
	echo -e "\n"
	echo "Downloading and parsing page..."
	
	# remove all html tegs, remove all dbg and dev versions, get Debian codename
	# P.S. sorry for this duck tape :/ I'm too lazy, fix later, mb
	wineVersionAmd64=$(cat /tmp/wine-staging.html | sed -e :a -e 's/<[^>]*>//g;/</N;//ba' | cut -f 1 -d ' ' | sed '/dev/d;/dbg/d;/winehq/d;/compat/d'\
	 | grep `lsb_release --codename | cut -f 2` | tail -n 4 | sed '3!D')
	wineVersionAmd64Libs=$(cat /tmp/wine-staging.html | sed -e :a -e 's/<[^>]*>//g;/</N;//ba' | cut -f 1 -d ' ' | sed '/dev/d;/dbg/d;/winehq/d;/compat/d'\
	 | grep `lsb_release --codename | cut -f 2` | tail -n 4 | sed '1!D')
	wineVersioni386=$(cat /tmp/wine-staging.html | sed -e :a -e 's/<[^>]*>//g;/</N;//ba' | cut -f 1 -d ' ' | sed '/dev/d;/dbg/d;/winehq/d;/compat/d'\
	 | grep `lsb_release --codename | cut -f 2` | tail -n 4 | sed '4!D')
	wineVersioni386Libs=$(cat /tmp/wine-staging.html | sed -e :a -e 's/<[^>]*>//g;/</N;//ba' | cut -f 1 -d ' ' | sed '/dev/d;/dbg/d;/winehq/d;/compat/d'\
	 | grep `lsb_release --codename | cut -f 2` | tail -n 4 | sed '2!D')
	
	echo -e "Done!\nDonwloading and unpaking wine..."
	
	dir="/tmp/wine-staging/"
	
	mkdir $dir
	
	if [[ ! -z `lsb_release | grep amd64` ]]; then
		echo "Script detected, that your system is amd64, so downloading 64bit wine."
		echo "Downloading wine..."
		# getting wine itself
		touch $dir$wineVersionAmd64
		wget -qO - http://cdn.fds-team.de/stable/debian/pool/main/w/wine-staging/$wineVersionAmd64 > $dir$wineVersionAmd64
		dpkg -x $dir$wineVersionAmd64 $dir
		rm $dir$wineVersionAmd64
		
		echo "Downloading libs..."
		# getting libs both 32x and 64x
		touch $dir$wineVersionAmd64Libs
		wget -qO - http://cdn.fds-team.de/stable/debian/pool/main/w/wine-staging/$wineVersioni386Libs > $dir$wineVersionAmd64Libs
		dpkg -x $dir$wineVersionAmd64Libs $dir
		rm $dir$wineVersionAmd64Libs
		
		touch $dir$wineVersioni386Libs
		wget -qO - http://cdn.fds-team.de/stable/debian/pool/main/w/wine-staging/$wineVersionAmd64Libs > $dir$wineVersioni386Libs
		dpkg -x $dir$wineVersioni386Libs $dir
		rm $dir$wineVersioni386Libs
	else
		echo "Script detected, that your system is i386, so downloading 32bit wine."
		echo "Downloading wine..."
		touch $dir$wineVersioni386
		wget -qO - http://cdn.fds-team.de/stable/debian/pool/main/w/wine-staging/$wineVersioni386 > $dir$wineVersioni386
		dpkg -x $dir$wineVersioni386 $dir
		rm $dir$wineVersioni386
		
		echo "Downloading libs..."
		touch $dir$wineVersioni386Libs
		wget -qO - http://cdn.fds-team.de/stable/debian/pool/main/w/wine-staging/$wineVersioni386Libs > $dir$wineVersioni386Libs
		dpkg -x $dir$wineVersioni386Libs $dir
		rm $dir$wineVersioni386Libs
	fi
	
	echo "Removing temporary data..."
	echo "Now script ask for su password (using sudo):"
	sleep 2
	sudo mv $dir"/opt/wine-staging" "/opt/wine_"$v
	
	rm -rf "/tmp/wine-staging"
	
	rm /tmp/wine-staging.html
	
	echo "All done! Your wine version now is $v."
}

if [ -z "$WINEPREFIX" ]; then
	WINEPREFIX=$wine_prefixes_dir$default_prefix
fi

prefix=`awk -F "=" '/#arch/ {print $2}' $WINEPREFIX/user.reg`

if [[ ! -z "$ARCH" || "$prefix" = "win32" ]]; then
	ww="wine"
	echo "msg: Use 32bit wine"
else
	ww="wine64"
	echo "msg: Use 64bit wine (by default)"
fi

if [ "$1" = "" ]; then
	help
	exit 0
elif [ "$1" = "--h" ]; then
	help 
	exit 0
elif [ "$1" = "--ver" ]; then
	echo "WINE helper version is $VER"
	exit 0
elif [[ "$1" = "--N" || "$1" = "--new-prefix" ]]; then
	WINEPREFIX=$WINEPREFIX $wine_path$ww wineboot
	exit 0
elif [ "$1" = "--check-wine-version" ]; then
	checkWineVersion
	exit 0;
fi

if [ -z $RUNTIME ]; then
	echo "msg: Use NO runtime. Remember, if you don't use multilib, some 32bit app may work incorrectly."
else
	echo "msg: Use \"$RUNTIME\" command to provide runtime."
fi

echo "msg: running wine verion $wine_ver_get"
WINEPREFIX=$WINEPREFIX $RUNTIME $wine_path$ww $1
