#!/bin/bash

function help() 
{
	echo "Usage: wine_set_shortcut
       wine-shortcut [-n=* -i=* -e=* -p=*]
       wine-shortcut -n | --name			        Set name
       wine-shortcut -i | --icon				Set icon
       wine-shortcut -e | --exec				Set execution
       wine-shortcut -p | --prefix				Set prefix
       

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY (c) 2015 Volk_Milit"
}

for i in "$@"; do
	case $i in
		-n=*|--name=*)
		name="${i#*=}"
		shift
		;;
		
		-e=*|--exec=*)
		exe="${i#*=}"
		shift
		;;
		
		-i=*|--icon=*)
		icon="${i#*=}"
		shift
		;;
		
		-p=*|--prefix=*)
		prefix="${i#*=}"
		shift
		;;
		
		-h|--help)
		help
		exit 0
		;;
esac
done

pwd=`echo ${PWD} | sed -e 's/.*/"&"/g'`
N=`echo $name | sed -e 's/ /_/g'`

touch "$HOME/.local/share/applications/Games/"$N".desktop"

cat > "$HOME/.local/share/applications/Games/"$N".desktop" <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=$name
Exec=sh -c 'cd ${pwd}; wine -p=$prefix $exe'
Icon=$icon
Categories=Game;

EOF
