#!/usr/bin/env bash

pwd=`echo ${PWD} | sed -e 's/.*/"&"/g'`

function help() 
{
	echo "Usage: $0
       $0 [-n=* -i=* -e=* -p=*]
       $0 -n | --name			        Set name
       $0 -i | --icon				Set icon
       $0 -e | --exec				Set execution
       $0 -p | --prefix				Set prefix
       $0 -a | --auto (exe)			Try auto mode (may not work as expected)
       

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY (c) 2015 Volk_Milit"
}

#https://notabug.org/kl3/scripts/src/master/build
function ask()
{
	echo -e "${1} [yN]: " 1>&2
	read REPLY
	[ "${REPLY}" = y ]
}

if [[ "$1" = "-a" || "$1" = "--auto" ]]; then
	ind=0
	exe_list=$(ls -l | egrep "*-*-x" | cut -d " " -f 11)
	
	if [ -z $2 ]; then
		ask "You did't specify exe path. Choose one of these:\n"
		for i in $F; do echo $((ind=ind+1)) $i; done
	else
		exe=$2
	fi
	
	tmp=`echo $pwd/$2 | sed 's|.*/||'`
	name=`basename "$(echo $pwd/$tmp | sed 's/\/'$tmp'//g;s/"//g')"`
	prefix=.wine_tesv
	
	if [[ -f "${PWD}/icon.ico" ]]; then
		convert "${PWD}/icon.ico" "${PWD}/icon.png"
	fi
	
	icon=${PWD}/icon.png
else
	for i in "$@"; do
		case $i in
			-n=*|--name=*)
			name="${i#*=}"
			shift
			;;
		
			-e=*|--exec=*)
			exe="${i#*=}"
			shift
			;;
		
			-i=*|--icon=*)
			icon="${i#*=}"
			shift
			;;
		
			-p=*|--prefix=*)
			prefix="${i#*=}"
			shift
			;;
		
			-h|--help)
			help
			exit 0
			;;
	esac
	done
fi

file="$HOME/.local/share/applications/Games/"`echo $name | sed -e 's/ /_/g'`".desktop"

touch $file

cat > $file <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=$name
Exec=sh -c 'cd ${pwd}; wine -p=$prefix $exe'
Icon=$icon
Categories=Game;

EOF
