#!/bin/sh

. /usr/local/lib/wine_helper/wine_helper_global.shlib

wine_prefixes_dir="$HOME/.local/share/wine_prefix/"
default_prefix=".wine64"

[ -f $conf ] && . $conf

sandboxing()
{
	[ -z $WINEPREFIX ] && $WINEPREFIX=$wine_prefixes_dir$default_prefix
	
	#array support for sh :D
	a="Мои документы;Мои рисунки;Мои фильмы;Моя музыка;Рабочий стол"
	
	for i in `seq 1 5`; do
		if [ -r "$WINEPREFIX/drive_c/users/$USER/$(array "$a" $i)" ]; then
			rm "$WINEPREFIX/drive_c/users/$USER/$(array "$a" $i)"
		fi
		ln -s "$fake_home" "$WINEPREFIX/drive_c/users/$USER/$(array "$a" $i)"
	done
}

deleteTrash()
{
	[ -z $WINEPREFIX ] && WINEPREFIX=$wine_prefixes_dir$default_prefix
	
	rm -rv $WINEPREFIX/drive_c/users/$USER/dd_*.txt
	rm -rv $WINEPREFIX/drive_c/users/$USER/uxeventlog.txt
	rm -rv $WINEPREFIX/drive_c/users/$USER/Cookies/*
	rm -rfv $WINEPREFIX/drive_c/users/$USER/Local Settings/Temporary Internet Files/Content.IE5/*
	rm -rfv $WINEPREFIX/drive_c/users/$USER/Temp/*
	rm -rv "$WINEPREFIX/drive_c/users/Public/Рабочий стол/"*
	rm -rfv "$WINEPREFIX/drive_c/Program Files (x86)/InstallShield Installation Information/"*
	rm -rv $WINEPREFIX/drive_c/eula*.txt
	rm -rv $WINEPREFIX/drive_c/install.res*.dll
}

deleteWineAssociations()
{
	rm $HOME/.local/share/applications/wine-extension*
	sed -i '/FileOpenAssociations/d;/AppName/d;/DesktopFile/d;/Associations/d;/MimeType/d;/OpenWithIcon/d;/ProgID/d' $WINEPREFIX/user.reg
}

for i in "$@"; do
	case $i in
		-wvs=*|--wine-ver-set=*)
		wine_path=$dir"wine_${i#*=}/bin/"
		shift
		;;
		
		-p=*|--prefix=*)
		WINEPREFIX=$wine_prefixes_dir"${i#*=}"
		shift
		;;
		
		-a=*|--arch=*)
		ARCH="${i#*=}"
		shift
		;;
		
		*)
		#help
		#exit 0
		;;
	esac
done

if [ "$1" = "--sandbox" ] || [ "$1" = "-s" ]; then
	sandboxing
	exit 0
elif [ "$1" = "--delete-trash" ]; then
	deleteTrash
	exit 0
elif [ "$1" = "--delete-junk-associations" ]; then
	deleteWineAssociations
	exit 0
elif [ "$1" = "-h" ]; then
	help
	exit 0
fi
