#!/bin/sh

. /usr/local/lib/wine_helper/wine_helper_global.shlib

pwd=`echo ${PWD} | sed -e 's/.*/"&"/g'`

if [ "$1" = "-a" ] || [ "$1" = "--auto" ]; then
	ind=0
	exe_list=$(ls -l | egrep "*-*-x" | cut -d " " -f 11)
	
	if [ -z $2 ]; then
		ask "You did't specify exe path. Choose one of these:\n"
		for i in $F; do echo $((ind=ind+1)) $i; done
	else
		exe=$2
	fi
	
	tmp=`echo $pwd/$2 | sed 's|.*/||'`
	name=`basename "$(echo $pwd/$tmp | sed 's/\/'$tmp'//g;s/"//g')"`
	prefix=".wine_tesv"
	
	if [ -f "${PWD}/icon.ico" ]; then
		convert "${PWD}/icon.ico" "${PWD}/icon.png"
		icon=${PWD}/icon.png
	else
		convert "${PWD}/$(ls | awk '/ico/')" "${PWD}/$(ls | awk 'gsub(".ico", "")').png"
		icon=${PWD}/$(ls | awk 'gsub(".ico", "")').png
	fi
elif [ "$1" = "" ]; then
	help
	exit 0
else
	for i in "$@"; do
		case $i in
			-n=*|--name=*)
			name="${i#*=}"
			shift
			;;
		
			-e=*|--exec=*)
			exe="${i#*=}"
			shift
			;;
		
			-i=*|--icon=*)
			icon="${i#*=}"
			shift
			;;
		
			-p=*|--prefix=*)
			prefix="${i#*=}"
			shift
			;;
		
			-h|--help)
			help
			exit 0
			;;
			
			*)
			help
			exit 0
			;;
	esac
	done
fi

file="$HOME/.local/share/applications/Games/"`echo $name | sed -e 's/ /_/g'`".desktop"

touch $file

cat > $file <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=$name
Exec=sh -c 'cd ${pwd}; wine -p=$prefix $exe'
Icon=$icon
Categories=Game;

EOF
