#!/bin/sh

. /usr/local/lib/wine_helper/wine_helper_global.shlib

wine_prefixes_dir="$HOME/.local/share/wine_prefix/"
default_prefix=".wine64"

[ -f $conf ] && . $conf
default_path=$wine_prefixes_dir$default_prefix

sandboxing()
{
	die
	
	local home_overwrite="$HOME/.fake_wine_home"
	local a1=("Мои документы" "Мои рисунки" "Мои фильмы" "Моя музыка" "Рабочий стол")

	for i in `seq 0 4`; do
		rm "$default_path/drive_c/users/$USER/${a1[i]}" 1>&2
		ln -s $home_overwrite "$default_path/drive_c/users/$USER/${a1[i]}" 1>&2
	done
}

deleteWineAssociations()
{
	rm $HOME/.local/share/applications/wine-extension*
	sed -i '/FileOpenAssociations/d;/AppName/d;/DesktopFile/d;/Associations/d;/MimeType/d;/OpenWithIcon/d;/ProgID/d' $WINEPREFIX/user.reg
}

for i in "$@"; do
	case $i in
		-wvs=*|--wine-ver-set=*)
		wine_path=$dir"wine_${i#*=}/bin/"
		shift
		;;
		
		-p=*|--prefix=*)
		WINEPREFIX=$wine_prefixes_dir"${i#*=}"
		shift
		;;
		
		-a=*|--arch=*)
		ARCH="${i#*=}"
		shift
		;;
		
		*)
		#help
		#exit 0
		;;
	esac
done

if [ "$1" = "--sandbox" ] || [ "$1" = "-S" ]; then
	sandboxing
	exit 0
elif [ "$1" = "--delete-junk-associations" ]; then
	deleteWineAssociations
	exit 0
elif [ "$1" = "-h" ]; then
	help
	exit 0
fi
