#!/bin/bash
conf=$HOME/.config/wine_helper/settings.conf

repo="https://dl.winehq.org/wine-builds/debian/pool/main/"
dir=/opt

if [ -f $conf ]; then
	dir=`awk -F "=" '/wine_dir/ {print $2}' $conf`
fi

wine_ver_get=`ls $dir | sort --version-sort | sed '/wine_/!d; $!d'` # get the lasted version of wine in dir, e.g. wine_1.8.0
wine_path=$dir$wine_ver_get"/bin/"

function getPOLLists()
{
		LIST="https://www.playonlinux.com/wine/binaries/linux-"$1".lst"
		curl $LIST | sed 's/.pol;[^ ]*//' > /tmp/list-$1.lst
		cat /tmp/list-$1.lst
		rm /tmp/list-$1.lst
}

# https://www.playonlinux.com/wine/binaries/
# both 32x and 64x
function getPOLWine()
{
		GET="https://www.playonlinux.com/wine/binaries/linux-"$1"/"$2".pol"
		wget -qO - $GET > /tmp/wine.tar.gz
		cd /tmp
		tar xvf wine.tar.gz
		rm -rf playonlinux
		rm -rf files
		ver=`ls wineversion`
		mv wineversion/* /opt/wine_$ver
}

# https://dl.winehq.org/wine-builds/debian/pool/main/
function getStagingWine()
{
	if [[ ! `which sudo` && `ls -ld $dir | cut -d ' ' -f3`!=whoami ]]; then
		echo "You don't have sudo installed in your system. Run $0 as root or change destanation folder."
		exit 0
	fi
	
	# get wine-staging page
	wget -qO - $repo > /tmp/wine-staging.html
	
	echo "================================"
	echo "Downloading lastes wine-staging"
	echo "================================"
	echo -e "\n"
	echo "Downloading and parsing page..."
	
	# remove all html tegs, remove all dbg and dev versions, get Debian codename
	# P.S. sorry for this duck tape :/ I'm too lazy, fix later, mb
	
	#black magic starts here
	removeTrash=`cat /tmp/wine-staging.html | sed -e :a -e 's/<[^>]*>//g;/</N;//ba;/dbg/d;/compat/d;/devel/d;/dev/d;/winehq/d' | grep $development".0"~$(lsb_release --codename | sed 's/Codename:\t//g') | cut -d 'b' -f 1 | sed 's/de/deb/g'`
	
	wineVersionAmd64=$(echo $removeTrash | cut -d ' ' -f3)
	wineVersionAmd64Libs=$(echo $removeTrash | cut -d ' ' -f1)
	wineVersioni386=$(echo $removeTrash | cut -d ' ' -f4)
	wineVersioni386Libs=$(echo $removeTrash | cut -d ' ' -f2)
	
	echo -e "Done!\nDonwloading and unpaking wine..."
	
	tmp_dir="/tmp/wine-staging/"
	mkdir $tmp_dir
	
	if [ `uname -m` == "x86_64" ]; then
		echo "Script detected, that your system is amd64, so downloading 64bit wine."
		echo "Downloading wine..."
		# getting wine itself
		touch $tmp_dir$wineVersionAmd64
		wget -qO - $repo$wineVersionAmd64 > $tmp_dir$wineVersionAmd64
		dpkg -x $tmp_dir$wineVersionAmd64 $tmp_dir
		#rm $dir$wineVersionAmd64
		
		echo "Downloading libs..."
		# getting libs both 32x and 64x
		touch $tmp_dir$wineVersionAmd64Libs
		wget -qO - $repo$wineVersioni386Libs > $tmp_dir$wineVersionAmd64Libs
		dpkg -x $tmp_dir$wineVersionAmd64Libs $tmp_dir
		#rm $dir$wineVersionAmd64Libs
		
		touch $tmp_dir$wineVersioni386Libs
		wget -qO - $repo$wineVersionAmd64Libs > $tmp_dir$wineVersioni386Libs
		dpkg -x $tmp_dir$wineVersioni386Libs $tmp_dir
		#rm $dir$wineVersioni386Libs
	else
		echo "Script detected, that your system is i386, so downloading 32bit wine."
		echo "Downloading wine..."
		touch $tmp_dir$wineVersioni386
		wget -qO - $repo$wineVersioni386 > $tmp_dir$wineVersioni386
		dpkg -x $dir$wineVersioni386 $tmp_dir
		rm $tmp_dir$wineVersioni386
		
		echo "Downloading libs..."
		touch $tmp_dir$wineVersioni386Libs
		wget -qO - $repo$wineVersioni386Libs > $tmp_dir$wineVersioni386Libs
		dpkg -x $tmp_dir$wineVersioni386Libs $tmp_dir
		rm $tmp_dir$wineVersioni386Libs
	fi
	
	echo "Removing temporary data..."
	echo "Now script ask for su password (using sudo):"
	sleep 1
	sudo mv $tmp_dir"opt/wine-staging" "/opt/wine_"$development
	
	rm -rf "/tmp/wine-staging"
	rm /tmp/wine-staging.html
	
	echo "All done! Your wine version now is $v."
}

function yesno()
{
	read ans
		
	case $ans in
		"no") exit 0;;
		"n") exit 0;;
		"N") exit 0;;
		"yes") getStagingWine;;
		"y") getStagingWine;;
		"Y") getStagingWine;;
		*) echo "Put (y)es or (n)o!"; yesno;;
	esac
}

function getWineVersions()
{
	# get wine-hq page to get current wine versions
	wget -qO - https://www.winehq.org/ > /tmp/wine-hq.html
	removeTrash=`cat /tmp/wine-hq.html | grep "Wine&nbsp;" | sed -e :a -e 's/<[^>]*>//g;/</N;//ba;s/Wine&nbsp;//g;s/ //g'`
	development=`echo $removeTrash | cut -d ' ' -f2`
	rm /tmp/wine-hq.html
}

getWineVersions
 
if [[ "wine_"$development = $wine_ver_get ]]; then
	echo "You have lastes wine staging version at this moment: $wine_ver_get"
	rm /tmp/wine-staging.html
	exit 0
else
	echo -e "New version ($development.0) are avalable! Do you want to download it?\n[Y(es)/n(o)]:"
	yesno
fi
