#!/bin/sh

. /usr/local/lib/wine_helper/wine_helper_global.shlib
. $conf

wine_ver_get=$(ls $dir | sort -n | sed '/wine/!d;$!d') # get the lasted version of wine in dir, e.g. wine_1.8.0
wine_path=$dir/$wine_ver_get/bin

if [ -z $(which winetricks) ]; then
	curl - https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks -o $HOME/.local/bin/winetricks
	chmod +x $HOME/.local/bin/winetricks
fi

[ "$1" = "-h" ] && help && exit 0

for i in "$@"; do
	case $i in
		-wvs=*|--wine-ver-set=*)
		wine_path=$dir"wine_${i#*=}/bin"
		shift
		;;
		
		-p=*|--prefix=*)
		WINEPREFIX=$wine_prefixes_dir/"${i#*=}"
		shift
		;;
		
		-a=*|--arch=*)
		ARCH="${i#*=}"
		shift
		;;
	esac
done

[ -z "$WINEPREFIX" ] && WINEPREFIX=$wine_prefixes_dir$default_prefix
prefix=$(awk -F "=" '/#arch/ {print $2}' $WINEPREFIX/user.reg)

export WINEPREFIX=$WINEPREFIX 
export WINE=$wine_path/wine
export WINESERVER=$wine_path/wineserver

$runtime winetricks "$@"
